id: PA39C380C
initial_creation_type: input
source_metadata:
  title: Hagiography of Rong ston Shes bya kun rig (1367–1449)
  author: གསེར་མདོག་པཎ་ཆེན་ཤཱཀྱ་མཆོག་ལྡན།
  description: 'Digital version 4.0 {Tibetan}; master xml (completed: 2012-09); head
    entries supplemented and linebreaks encoded, revision in process, no thematic
    TEI markup'
  source: https://sakyaresearch.org
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Volker Caumanns (vc)
  - Editorial process:Volker Caumanns (vc), Mathias Fermer (mf)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:Volker Caumanns (vc)
  text_witnesses: https://sakyaresearch.org/sources/359
  bases:
    d3ef:
      title: Hagiography of Rong ston Shes bya kun rig (1367–1449)
      order: 1
      base_file: d3ef.txt
created_at: '2022-04-15T19:02:57.349155'
last_modified_at: '2022-04-15T19:02:57.349162'
quality: null
